Result
Gautam2305/quizmee_mini_app pull request #4
Opened 2022-02-17 17:19 UTC by Gautam2305

- shows score of the individual 
- shows the selected option and the correct option for all questions so that the user can analyze his/her answers

![Screenshot (133)](https://user-images.githubusercontent.com/95231941/154535541-9d659ad3-fec2-4c61-a2e7-38612d1a484b.png)

![Screenshot (134)](https://user-images.githubusercontent.com/95231941/154535470-bdd08a4d-9028-4458-a15b-0eeca208223b.png)

2022-02-17 17:25 UTC, shuntzhere requested changes
Very cleanly written HTML code. Suggested a minor change to be made.

2022-02-17 17:25 UTC, shuntzhere commented on pages/result/result.html
> +                <h4 class="text-white">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras fermentum euismod neque quis vehicula ?</h4>
The center class name is very generic. This could mean anything from align-items to text-align and even other ones. Give it a more meaningful name.

2022-02-17 17:29 UTC, coldpigli approved these changes
Everything looks good. I also have the same comment as Masoom's. The center class is a very generic name. Can be changed to something more specific. Everything else looks good.

2022-02-17 17:33 UTC, Gautam2305 commented on pages/result/result.html
> +                <h4 class="text-white">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras fermentum euismod neque quis vehicula ?</h4>
okay....will change that now

2022-02-17 20:00 UTC, Gautam2305 commented on pages/result/result.html
> +                <h4 class="text-white">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras fermentum euismod neque quis vehicula ?</h4>
done

2022-02-18 04:07 UTC, shuntzhere approved these changes
Looks good for the merge.

2022-02-18 05:00 UTC, merged